// source: jupiter/datastream/v1/order_queue.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var jupiter_datastream_v1_market_pb = require('../../../jupiter/datastream/v1/market_pb.js');
goog.object.extend(proto, jupiter_datastream_v1_market_pb);
goog.exportSymbol('proto.jupiter.datastream.v1.OrderQueue', null, global);
goog.exportSymbol('proto.jupiter.datastream.v1.OrderQueue.Side', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jupiter.datastream.v1.OrderQueue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jupiter.datastream.v1.OrderQueue.repeatedFields_, null);
};
goog.inherits(proto.jupiter.datastream.v1.OrderQueue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jupiter.datastream.v1.OrderQueue.displayName = 'proto.jupiter.datastream.v1.OrderQueue';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jupiter.datastream.v1.OrderQueue.repeatedFields_ = [10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.toObject = function(opt_includeInstance) {
  return proto.jupiter.datastream.v1.OrderQueue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jupiter.datastream.v1.OrderQueue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jupiter.datastream.v1.OrderQueue.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, ""),
    market: jspb.Message.getFieldWithDefault(msg, 2, 0),
    date: jspb.Message.getFieldWithDefault(msg, 3, 0),
    time: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    tradedate: jspb.Message.getFieldWithDefault(msg, 6, 0),
    orderside: jspb.Message.getFieldWithDefault(msg, 7, 0),
    orderprice: jspb.Message.getFieldWithDefault(msg, 8, 0),
    numorders: jspb.Message.getFieldWithDefault(msg, 9, 0),
    bidlevelqueueList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    offerlevelqueueList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jupiter.datastream.v1.OrderQueue}
 */
proto.jupiter.datastream.v1.OrderQueue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jupiter.datastream.v1.OrderQueue;
  return proto.jupiter.datastream.v1.OrderQueue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jupiter.datastream.v1.OrderQueue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jupiter.datastream.v1.OrderQueue}
 */
proto.jupiter.datastream.v1.OrderQueue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {!proto.jupiter.datastream.v1.MarketEnum.Market} */ (reader.readEnum());
      msg.setMarket(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTime(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTradedate(value);
      break;
    case 7:
      var value = /** @type {!proto.jupiter.datastream.v1.OrderQueue.Side} */ (reader.readEnum());
      msg.setOrderside(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOrderprice(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumorders(value);
      break;
    case 10:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setBidlevelqueueList(value);
      break;
    case 11:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setOfferlevelqueueList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jupiter.datastream.v1.OrderQueue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jupiter.datastream.v1.OrderQueue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jupiter.datastream.v1.OrderQueue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMarket();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDate();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTradedate();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getOrderside();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getOrderprice();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getNumorders();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getBidlevelqueueList();
  if (f.length > 0) {
    writer.writePackedUint64(
      10,
      f
    );
  }
  f = message.getOfferlevelqueueList();
  if (f.length > 0) {
    writer.writePackedUint64(
      11,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.jupiter.datastream.v1.OrderQueue.Side = {
  BID: 0,
  OFFER: 1
};

/**
 * optional string code = 1;
 * @return {string}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional MarketEnum.Market market = 2;
 * @return {!proto.jupiter.datastream.v1.MarketEnum.Market}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getMarket = function() {
  return /** @type {!proto.jupiter.datastream.v1.MarketEnum.Market} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.jupiter.datastream.v1.MarketEnum.Market} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setMarket = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional uint32 date = 3;
 * @return {number}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setDate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 time = 4;
 * @return {number}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setTime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
*/
proto.jupiter.datastream.v1.OrderQueue.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint32 tradeDate = 6;
 * @return {number}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getTradedate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setTradedate = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional Side orderSide = 7;
 * @return {!proto.jupiter.datastream.v1.OrderQueue.Side}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getOrderside = function() {
  return /** @type {!proto.jupiter.datastream.v1.OrderQueue.Side} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.jupiter.datastream.v1.OrderQueue.Side} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setOrderside = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional uint32 orderPrice = 8;
 * @return {number}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getOrderprice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setOrderprice = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 numOrders = 9;
 * @return {number}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getNumorders = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setNumorders = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * repeated uint64 bidLevelQueue = 10;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getBidlevelqueueList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setBidlevelqueueList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.addBidlevelqueue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.clearBidlevelqueueList = function() {
  return this.setBidlevelqueueList([]);
};


/**
 * repeated uint64 offerLevelQueue = 11;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.getOfferlevelqueueList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.setOfferlevelqueueList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.addOfferlevelqueue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.OrderQueue} returns this
 */
proto.jupiter.datastream.v1.OrderQueue.prototype.clearOfferlevelqueueList = function() {
  return this.setOfferlevelqueueList([]);
};


goog.object.extend(exports, proto.jupiter.datastream.v1);
