// source: jupiter/datastream/v1/stock_data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var jupiter_datastream_v1_market_pb = require('../../../jupiter/datastream/v1/market_pb.js');
goog.object.extend(proto, jupiter_datastream_v1_market_pb);
goog.exportSymbol('proto.jupiter.datastream.v1.StockData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jupiter.datastream.v1.StockData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jupiter.datastream.v1.StockData.repeatedFields_, null);
};
goog.inherits(proto.jupiter.datastream.v1.StockData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jupiter.datastream.v1.StockData.displayName = 'proto.jupiter.datastream.v1.StockData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jupiter.datastream.v1.StockData.repeatedFields_ = [47,48,49,50,51,52];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jupiter.datastream.v1.StockData.prototype.toObject = function(opt_includeInstance) {
  return proto.jupiter.datastream.v1.StockData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jupiter.datastream.v1.StockData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jupiter.datastream.v1.StockData.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, ""),
    market: jspb.Message.getFieldWithDefault(msg, 2, 0),
    date: jspb.Message.getFieldWithDefault(msg, 3, 0),
    time: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    tradedate: jspb.Message.getFieldWithDefault(msg, 6, 0),
    preclosepx: jspb.Message.getFieldWithDefault(msg, 7, 0),
    openpx: jspb.Message.getFieldWithDefault(msg, 8, 0),
    highpx: jspb.Message.getFieldWithDefault(msg, 9, 0),
    lowpx: jspb.Message.getFieldWithDefault(msg, 10, 0),
    lastpx: jspb.Message.getFieldWithDefault(msg, 11, 0),
    closepx: jspb.Message.getFieldWithDefault(msg, 12, 0),
    instrumentstatus: jspb.Message.getFieldWithDefault(msg, 13, ""),
    tradingphasecode: jspb.Message.getFieldWithDefault(msg, 14, ""),
    numtrades: jspb.Message.getFieldWithDefault(msg, 15, 0),
    totalvolumetrade: jspb.Message.getFieldWithDefault(msg, 16, 0),
    totalvaluetrade: jspb.Message.getFieldWithDefault(msg, 17, 0),
    totalbidqty: jspb.Message.getFieldWithDefault(msg, 18, 0),
    totalofferqty: jspb.Message.getFieldWithDefault(msg, 19, 0),
    weightedavgbidpx: jspb.Message.getFieldWithDefault(msg, 20, 0),
    weightedavgofferpx: jspb.Message.getFieldWithDefault(msg, 21, 0),
    altweightedavgbidpx: jspb.Message.getFieldWithDefault(msg, 22, 0),
    altweightedavgofferpx: jspb.Message.getFieldWithDefault(msg, 23, 0),
    iopv: jspb.Message.getFieldWithDefault(msg, 24, 0),
    yieldtomaturity: jspb.Message.getFieldWithDefault(msg, 25, 0),
    totalwarrantexecqty: jspb.Message.getFieldWithDefault(msg, 26, 0),
    warlowerpx: jspb.Message.getFieldWithDefault(msg, 27, 0),
    warupperpx: jspb.Message.getFieldWithDefault(msg, 28, 0),
    etfbuynumber: jspb.Message.getFieldWithDefault(msg, 29, 0),
    etfbuyamount: jspb.Message.getFieldWithDefault(msg, 30, 0),
    etfbuymoney: jspb.Message.getFieldWithDefault(msg, 31, 0),
    etfsellnumber: jspb.Message.getFieldWithDefault(msg, 32, 0),
    etfsellamount: jspb.Message.getFieldWithDefault(msg, 33, 0),
    etfsellmoney: jspb.Message.getFieldWithDefault(msg, 34, 0),
    withdrawbuynumber: jspb.Message.getFieldWithDefault(msg, 35, 0),
    withdrawbuyamount: jspb.Message.getFieldWithDefault(msg, 36, 0),
    withdrawbuymoney: jspb.Message.getFieldWithDefault(msg, 37, 0),
    withdrawsellnumber: jspb.Message.getFieldWithDefault(msg, 38, 0),
    withdrawsellamount: jspb.Message.getFieldWithDefault(msg, 39, 0),
    withdrawsellmoney: jspb.Message.getFieldWithDefault(msg, 40, 0),
    totalbidnumber: jspb.Message.getFieldWithDefault(msg, 41, 0),
    totaloffernumber: jspb.Message.getFieldWithDefault(msg, 42, 0),
    bidtrademaxduration: jspb.Message.getFieldWithDefault(msg, 43, 0),
    offertrademaxduration: jspb.Message.getFieldWithDefault(msg, 44, 0),
    numbidorders: jspb.Message.getFieldWithDefault(msg, 45, 0),
    numofferorders: jspb.Message.getFieldWithDefault(msg, 46, 0),
    bidpriceList: (f = jspb.Message.getRepeatedField(msg, 47)) == null ? undefined : f,
    bidqtyList: (f = jspb.Message.getRepeatedField(msg, 48)) == null ? undefined : f,
    bidnumordersList: (f = jspb.Message.getRepeatedField(msg, 49)) == null ? undefined : f,
    offerpriceList: (f = jspb.Message.getRepeatedField(msg, 50)) == null ? undefined : f,
    offerqtyList: (f = jspb.Message.getRepeatedField(msg, 51)) == null ? undefined : f,
    offernumordersList: (f = jspb.Message.getRepeatedField(msg, 52)) == null ? undefined : f,
    priceuplimit: jspb.Message.getFieldWithDefault(msg, 53, 0),
    pricedownlimit: jspb.Message.getFieldWithDefault(msg, 54, 0),
    priceupdown1: jspb.Message.getFieldWithDefault(msg, 55, 0),
    priceupdown2: jspb.Message.getFieldWithDefault(msg, 56, 0),
    peratio1: jspb.Message.getFieldWithDefault(msg, 57, 0),
    peratio2: jspb.Message.getFieldWithDefault(msg, 58, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jupiter.datastream.v1.StockData}
 */
proto.jupiter.datastream.v1.StockData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jupiter.datastream.v1.StockData;
  return proto.jupiter.datastream.v1.StockData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jupiter.datastream.v1.StockData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jupiter.datastream.v1.StockData}
 */
proto.jupiter.datastream.v1.StockData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {!proto.jupiter.datastream.v1.MarketEnum.Market} */ (reader.readEnum());
      msg.setMarket(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTime(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTradedate(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPreclosepx(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setOpenpx(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setHighpx(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLowpx(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastpx(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setClosepx(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstrumentstatus(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setTradingphasecode(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNumtrades(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalvolumetrade(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalvaluetrade(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalbidqty(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalofferqty(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWeightedavgbidpx(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWeightedavgofferpx(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAltweightedavgbidpx(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAltweightedavgofferpx(value);
      break;
    case 24:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIopv(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setYieldtomaturity(value);
      break;
    case 26:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalwarrantexecqty(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWarlowerpx(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWarupperpx(value);
      break;
    case 29:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEtfbuynumber(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEtfbuyamount(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEtfbuymoney(value);
      break;
    case 32:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEtfsellnumber(value);
      break;
    case 33:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEtfsellamount(value);
      break;
    case 34:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEtfsellmoney(value);
      break;
    case 35:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWithdrawbuynumber(value);
      break;
    case 36:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWithdrawbuyamount(value);
      break;
    case 37:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWithdrawbuymoney(value);
      break;
    case 38:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWithdrawsellnumber(value);
      break;
    case 39:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWithdrawsellamount(value);
      break;
    case 40:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWithdrawsellmoney(value);
      break;
    case 41:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTotalbidnumber(value);
      break;
    case 42:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTotaloffernumber(value);
      break;
    case 43:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBidtrademaxduration(value);
      break;
    case 44:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffertrademaxduration(value);
      break;
    case 45:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumbidorders(value);
      break;
    case 46:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumofferorders(value);
      break;
    case 47:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setBidpriceList(value);
      break;
    case 48:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setBidqtyList(value);
      break;
    case 49:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setBidnumordersList(value);
      break;
    case 50:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setOfferpriceList(value);
      break;
    case 51:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setOfferqtyList(value);
      break;
    case 52:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setOffernumordersList(value);
      break;
    case 53:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPriceuplimit(value);
      break;
    case 54:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPricedownlimit(value);
      break;
    case 55:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPriceupdown1(value);
      break;
    case 56:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPriceupdown2(value);
      break;
    case 57:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPeratio1(value);
      break;
    case 58:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPeratio2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jupiter.datastream.v1.StockData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jupiter.datastream.v1.StockData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jupiter.datastream.v1.StockData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jupiter.datastream.v1.StockData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMarket();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDate();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTradedate();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getPreclosepx();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getOpenpx();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getHighpx();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getLowpx();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getLastpx();
  if (f !== 0) {
    writer.writeUint64(
      11,
      f
    );
  }
  f = message.getClosepx();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getInstrumentstatus();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getTradingphasecode();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getNumtrades();
  if (f !== 0) {
    writer.writeUint64(
      15,
      f
    );
  }
  f = message.getTotalvolumetrade();
  if (f !== 0) {
    writer.writeUint64(
      16,
      f
    );
  }
  f = message.getTotalvaluetrade();
  if (f !== 0) {
    writer.writeUint64(
      17,
      f
    );
  }
  f = message.getTotalbidqty();
  if (f !== 0) {
    writer.writeUint64(
      18,
      f
    );
  }
  f = message.getTotalofferqty();
  if (f !== 0) {
    writer.writeUint64(
      19,
      f
    );
  }
  f = message.getWeightedavgbidpx();
  if (f !== 0) {
    writer.writeUint64(
      20,
      f
    );
  }
  f = message.getWeightedavgofferpx();
  if (f !== 0) {
    writer.writeUint64(
      21,
      f
    );
  }
  f = message.getAltweightedavgbidpx();
  if (f !== 0) {
    writer.writeUint64(
      22,
      f
    );
  }
  f = message.getAltweightedavgofferpx();
  if (f !== 0) {
    writer.writeUint64(
      23,
      f
    );
  }
  f = message.getIopv();
  if (f !== 0) {
    writer.writeUint64(
      24,
      f
    );
  }
  f = message.getYieldtomaturity();
  if (f !== 0) {
    writer.writeUint64(
      25,
      f
    );
  }
  f = message.getTotalwarrantexecqty();
  if (f !== 0) {
    writer.writeUint64(
      26,
      f
    );
  }
  f = message.getWarlowerpx();
  if (f !== 0) {
    writer.writeUint64(
      27,
      f
    );
  }
  f = message.getWarupperpx();
  if (f !== 0) {
    writer.writeUint64(
      28,
      f
    );
  }
  f = message.getEtfbuynumber();
  if (f !== 0) {
    writer.writeUint32(
      29,
      f
    );
  }
  f = message.getEtfbuyamount();
  if (f !== 0) {
    writer.writeUint64(
      30,
      f
    );
  }
  f = message.getEtfbuymoney();
  if (f !== 0) {
    writer.writeUint64(
      31,
      f
    );
  }
  f = message.getEtfsellnumber();
  if (f !== 0) {
    writer.writeUint32(
      32,
      f
    );
  }
  f = message.getEtfsellamount();
  if (f !== 0) {
    writer.writeUint64(
      33,
      f
    );
  }
  f = message.getEtfsellmoney();
  if (f !== 0) {
    writer.writeUint64(
      34,
      f
    );
  }
  f = message.getWithdrawbuynumber();
  if (f !== 0) {
    writer.writeUint32(
      35,
      f
    );
  }
  f = message.getWithdrawbuyamount();
  if (f !== 0) {
    writer.writeUint64(
      36,
      f
    );
  }
  f = message.getWithdrawbuymoney();
  if (f !== 0) {
    writer.writeUint64(
      37,
      f
    );
  }
  f = message.getWithdrawsellnumber();
  if (f !== 0) {
    writer.writeUint32(
      38,
      f
    );
  }
  f = message.getWithdrawsellamount();
  if (f !== 0) {
    writer.writeUint64(
      39,
      f
    );
  }
  f = message.getWithdrawsellmoney();
  if (f !== 0) {
    writer.writeUint64(
      40,
      f
    );
  }
  f = message.getTotalbidnumber();
  if (f !== 0) {
    writer.writeUint32(
      41,
      f
    );
  }
  f = message.getTotaloffernumber();
  if (f !== 0) {
    writer.writeUint32(
      42,
      f
    );
  }
  f = message.getBidtrademaxduration();
  if (f !== 0) {
    writer.writeUint32(
      43,
      f
    );
  }
  f = message.getOffertrademaxduration();
  if (f !== 0) {
    writer.writeUint32(
      44,
      f
    );
  }
  f = message.getNumbidorders();
  if (f !== 0) {
    writer.writeUint32(
      45,
      f
    );
  }
  f = message.getNumofferorders();
  if (f !== 0) {
    writer.writeUint32(
      46,
      f
    );
  }
  f = message.getBidpriceList();
  if (f.length > 0) {
    writer.writePackedUint64(
      47,
      f
    );
  }
  f = message.getBidqtyList();
  if (f.length > 0) {
    writer.writePackedUint64(
      48,
      f
    );
  }
  f = message.getBidnumordersList();
  if (f.length > 0) {
    writer.writePackedUint32(
      49,
      f
    );
  }
  f = message.getOfferpriceList();
  if (f.length > 0) {
    writer.writePackedUint64(
      50,
      f
    );
  }
  f = message.getOfferqtyList();
  if (f.length > 0) {
    writer.writePackedUint64(
      51,
      f
    );
  }
  f = message.getOffernumordersList();
  if (f.length > 0) {
    writer.writePackedUint32(
      52,
      f
    );
  }
  f = message.getPriceuplimit();
  if (f !== 0) {
    writer.writeUint64(
      53,
      f
    );
  }
  f = message.getPricedownlimit();
  if (f !== 0) {
    writer.writeUint64(
      54,
      f
    );
  }
  f = message.getPriceupdown1();
  if (f !== 0) {
    writer.writeUint64(
      55,
      f
    );
  }
  f = message.getPriceupdown2();
  if (f !== 0) {
    writer.writeUint64(
      56,
      f
    );
  }
  f = message.getPeratio1();
  if (f !== 0) {
    writer.writeUint32(
      57,
      f
    );
  }
  f = message.getPeratio2();
  if (f !== 0) {
    writer.writeUint32(
      58,
      f
    );
  }
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.jupiter.datastream.v1.StockData.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional MarketEnum.Market market = 2;
 * @return {!proto.jupiter.datastream.v1.MarketEnum.Market}
 */
proto.jupiter.datastream.v1.StockData.prototype.getMarket = function() {
  return /** @type {!proto.jupiter.datastream.v1.MarketEnum.Market} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.jupiter.datastream.v1.MarketEnum.Market} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setMarket = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional uint32 date = 3;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setDate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 time = 4;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
*/
proto.jupiter.datastream.v1.StockData.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jupiter.datastream.v1.StockData.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint32 tradeDate = 6;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTradedate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTradedate = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 preClosePx = 7;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPreclosepx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPreclosepx = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint64 openPx = 8;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getOpenpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setOpenpx = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint64 highPx = 9;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getHighpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setHighpx = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint64 lowPx = 10;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getLowpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setLowpx = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint64 lastPx = 11;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getLastpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setLastpx = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint64 closePx = 12;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getClosepx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setClosepx = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string instrumentStatus = 13;
 * @return {string}
 */
proto.jupiter.datastream.v1.StockData.prototype.getInstrumentstatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setInstrumentstatus = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string tradingPhaseCode = 14;
 * @return {string}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTradingphasecode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTradingphasecode = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional uint64 numTrades = 15;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getNumtrades = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setNumtrades = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional uint64 totalVolumeTrade = 16;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotalvolumetrade = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotalvolumetrade = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional uint64 totalValueTrade = 17;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotalvaluetrade = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotalvaluetrade = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional uint64 totalBidQty = 18;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotalbidqty = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotalbidqty = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional uint64 totalOfferQty = 19;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotalofferqty = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotalofferqty = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint64 weightedAvgBidPx = 20;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWeightedavgbidpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWeightedavgbidpx = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional uint64 weightedAvgOfferPx = 21;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWeightedavgofferpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWeightedavgofferpx = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional uint64 altWeightedAvgBidPx = 22;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getAltweightedavgbidpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setAltweightedavgbidpx = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional uint64 altWeightedAvgOfferPx = 23;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getAltweightedavgofferpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setAltweightedavgofferpx = function(value) {
  return jspb.Message.setProto3IntField(this, 23, value);
};


/**
 * optional uint64 IOPV = 24;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getIopv = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 24, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setIopv = function(value) {
  return jspb.Message.setProto3IntField(this, 24, value);
};


/**
 * optional uint64 yieldToMaturity = 25;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getYieldtomaturity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setYieldtomaturity = function(value) {
  return jspb.Message.setProto3IntField(this, 25, value);
};


/**
 * optional uint64 totalWarrantExecQty = 26;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotalwarrantexecqty = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotalwarrantexecqty = function(value) {
  return jspb.Message.setProto3IntField(this, 26, value);
};


/**
 * optional uint64 warLowerPx = 27;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWarlowerpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWarlowerpx = function(value) {
  return jspb.Message.setProto3IntField(this, 27, value);
};


/**
 * optional uint64 warUpperPx = 28;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWarupperpx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWarupperpx = function(value) {
  return jspb.Message.setProto3IntField(this, 28, value);
};


/**
 * optional uint32 etfBuyNumber = 29;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getEtfbuynumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 29, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setEtfbuynumber = function(value) {
  return jspb.Message.setProto3IntField(this, 29, value);
};


/**
 * optional uint64 etfBuyAmount = 30;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getEtfbuyamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setEtfbuyamount = function(value) {
  return jspb.Message.setProto3IntField(this, 30, value);
};


/**
 * optional uint64 etfBuyMoney = 31;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getEtfbuymoney = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setEtfbuymoney = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * optional uint32 etfSellNumber = 32;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getEtfsellnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 32, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setEtfsellnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 32, value);
};


/**
 * optional uint64 etfSellAmount = 33;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getEtfsellamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 33, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setEtfsellamount = function(value) {
  return jspb.Message.setProto3IntField(this, 33, value);
};


/**
 * optional uint64 etfSellMoney = 34;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getEtfsellmoney = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 34, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setEtfsellmoney = function(value) {
  return jspb.Message.setProto3IntField(this, 34, value);
};


/**
 * optional uint32 withdrawBuyNumber = 35;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWithdrawbuynumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 35, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWithdrawbuynumber = function(value) {
  return jspb.Message.setProto3IntField(this, 35, value);
};


/**
 * optional uint64 withdrawBuyAmount = 36;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWithdrawbuyamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 36, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWithdrawbuyamount = function(value) {
  return jspb.Message.setProto3IntField(this, 36, value);
};


/**
 * optional uint64 withdrawBuyMoney = 37;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWithdrawbuymoney = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 37, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWithdrawbuymoney = function(value) {
  return jspb.Message.setProto3IntField(this, 37, value);
};


/**
 * optional uint32 withdrawSellNumber = 38;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWithdrawsellnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 38, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWithdrawsellnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 38, value);
};


/**
 * optional uint64 withdrawSellAmount = 39;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWithdrawsellamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 39, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWithdrawsellamount = function(value) {
  return jspb.Message.setProto3IntField(this, 39, value);
};


/**
 * optional uint64 withdrawSellMoney = 40;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getWithdrawsellmoney = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 40, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setWithdrawsellmoney = function(value) {
  return jspb.Message.setProto3IntField(this, 40, value);
};


/**
 * optional uint32 totalBidNumber = 41;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotalbidnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 41, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotalbidnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 41, value);
};


/**
 * optional uint32 totalOfferNumber = 42;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getTotaloffernumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 42, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setTotaloffernumber = function(value) {
  return jspb.Message.setProto3IntField(this, 42, value);
};


/**
 * optional uint32 bidTradeMaxDuration = 43;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getBidtrademaxduration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 43, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setBidtrademaxduration = function(value) {
  return jspb.Message.setProto3IntField(this, 43, value);
};


/**
 * optional uint32 OfferTradeMaxDuration = 44;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getOffertrademaxduration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 44, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setOffertrademaxduration = function(value) {
  return jspb.Message.setProto3IntField(this, 44, value);
};


/**
 * optional uint32 numBidOrders = 45;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getNumbidorders = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 45, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setNumbidorders = function(value) {
  return jspb.Message.setProto3IntField(this, 45, value);
};


/**
 * optional uint32 numOfferOrders = 46;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getNumofferorders = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 46, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setNumofferorders = function(value) {
  return jspb.Message.setProto3IntField(this, 46, value);
};


/**
 * repeated uint64 bidPrice = 47;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.StockData.prototype.getBidpriceList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 47));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setBidpriceList = function(value) {
  return jspb.Message.setField(this, 47, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.addBidprice = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 47, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearBidpriceList = function() {
  return this.setBidpriceList([]);
};


/**
 * repeated uint64 bidQty = 48;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.StockData.prototype.getBidqtyList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 48));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setBidqtyList = function(value) {
  return jspb.Message.setField(this, 48, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.addBidqty = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 48, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearBidqtyList = function() {
  return this.setBidqtyList([]);
};


/**
 * repeated uint32 bidNumOrders = 49;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.StockData.prototype.getBidnumordersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 49));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setBidnumordersList = function(value) {
  return jspb.Message.setField(this, 49, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.addBidnumorders = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 49, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearBidnumordersList = function() {
  return this.setBidnumordersList([]);
};


/**
 * repeated uint64 offerPrice = 50;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.StockData.prototype.getOfferpriceList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 50));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setOfferpriceList = function(value) {
  return jspb.Message.setField(this, 50, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.addOfferprice = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 50, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearOfferpriceList = function() {
  return this.setOfferpriceList([]);
};


/**
 * repeated uint64 offerQty = 51;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.StockData.prototype.getOfferqtyList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 51));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setOfferqtyList = function(value) {
  return jspb.Message.setField(this, 51, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.addOfferqty = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 51, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearOfferqtyList = function() {
  return this.setOfferqtyList([]);
};


/**
 * repeated uint32 offerNumOrders = 52;
 * @return {!Array<number>}
 */
proto.jupiter.datastream.v1.StockData.prototype.getOffernumordersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 52));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setOffernumordersList = function(value) {
  return jspb.Message.setField(this, 52, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.addOffernumorders = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 52, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.clearOffernumordersList = function() {
  return this.setOffernumordersList([]);
};


/**
 * optional uint64 priceUpLimit = 53;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPriceuplimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 53, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPriceuplimit = function(value) {
  return jspb.Message.setProto3IntField(this, 53, value);
};


/**
 * optional uint64 priceDownLimit = 54;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPricedownlimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 54, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPricedownlimit = function(value) {
  return jspb.Message.setProto3IntField(this, 54, value);
};


/**
 * optional uint64 priceUpDown1 = 55;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPriceupdown1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 55, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPriceupdown1 = function(value) {
  return jspb.Message.setProto3IntField(this, 55, value);
};


/**
 * optional uint64 priceUpDown2 = 56;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPriceupdown2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 56, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPriceupdown2 = function(value) {
  return jspb.Message.setProto3IntField(this, 56, value);
};


/**
 * optional uint32 peRatio1 = 57;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPeratio1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 57, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPeratio1 = function(value) {
  return jspb.Message.setProto3IntField(this, 57, value);
};


/**
 * optional uint32 peRatio2 = 58;
 * @return {number}
 */
proto.jupiter.datastream.v1.StockData.prototype.getPeratio2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 58, 0));
};


/**
 * @param {number} value
 * @return {!proto.jupiter.datastream.v1.StockData} returns this
 */
proto.jupiter.datastream.v1.StockData.prototype.setPeratio2 = function(value) {
  return jspb.Message.setProto3IntField(this, 58, value);
};


goog.object.extend(exports, proto.jupiter.datastream.v1);
